export const GET_PROFILE = 'GET_PROFILE'
export const GET_RESULTS ='GET_RESULTS'
export const RESULTS_ERROR = 'RESULTS_ERROR'
export const REMOVE_ALERT ='REMOVE_ALERT'
export const SET_ALERT = 'SET_ALERT'